
services:
  purostill-frontend:
    container_name: purostill-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORDPRESS_GRAPHQL_URL: https://backend-ps.purostill.com/graphql
        WOOCOMMERCE_URL: https://backend-ps.purostill.com
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WORDPRESS_GRAPHQL_URL=https://backend-ps.purostill.com/graphql
      - PORT=3000
      - HOSTNAME=0.0.0.0

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - purostill-frontend

volumes:
  caddy_data:
  caddy_config:
